name: spoosk
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  firebase_crashlytics: ^3.3.6
  firebase_core: ^2.16.0
  flutter_svg: ^2.0.7
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/comparison.svg
    - assets/img/home.svg
    - assets/img/profile.svg
    - assets/img/search.svg
    - assets/img/selected.svg

flutter_intl:
  enabled: true
