name: spoosk
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  firebase_crashlytics: ^3.3.6
  firebase_core: ^2.16.0
  flutter_svg: ^2.0.7
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  connectivity_plus: ^5.0.1
  carousel_slider: ^4.2.1
  visibility_detector: ^0.4.0+2
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.1
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
        - asset: assets/fonts/NunitoSans_10pt-SemiBold.ttf
    - family: Raleway
      fonts: 
        - asset: assets/fonts/Raleway-Medium.ttf


flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/core/presentation/l10n
  output_dir: lib/core/generated
